
services:
  laravel:
    restart: unless-stopped
    container_name: laravelapp
    build:
      context: ../
      dockerfile: ../Dockerfile
    env_file: ../.env
    volumes:
      - ../:/var/www/html
    ports:
      - "8080:80"
    networks:
      - n-laravel
    depends_on:
      - database

  database:
    container_name: laravel_db
    restart: unless-stopped
    image: mysql
    volumes:
      - v-database:/var/lib/mysql
    env_file: ../.env
    networks:
      - n-laravel

volumes:
  v-database:


networks:
  n-laravel:
    driver: bridge